# Generated by Django 5.1.2 on 2025-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
