# Generated by Django 5.1.2 on 2025-11-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_id", models.IntegerField(db_index=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
                ),
                ("last_attempt_at", models.DateTimeField(verbose_name="تاریخ آخرین تلاش")),
                (
                    "attempts_num",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تلاش\u200cها"),
                ),
                ("service_error", models.TextField(verbose_name="خطای سرویس")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ساخته شده"),
                            ("in_queue", "در صف ارسال"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                            ("failed", "خطا در ارسال"),
                            ("user_canceled", "کاربر لغو کرده"),
                            ("user_blocked", "کاربر بلاک کرده"),
                        ],
                        default="created",
                        max_length=255,
                        verbose_name="وضعیت",
                    ),
                ),
                ("receiver", models.CharField(max_length=255, verbose_name="شماره گیرنده")),
                ("content", models.TextField(verbose_name="محتوای پیام")),
                ("cost", models.BigIntegerField(verbose_name="هزینه (ریال)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامک",
                "verbose_name_plural": "پیامک\u200cها",
                "db_table": "SMS",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="sms_user_idx"),
                    models.Index(fields=["user", "status"], name="sms_user_status_idx"),
                    models.Index(fields=["user", "created_at"], name="sms_user_created_at_idx"),
                    models.Index(fields=["receiver"], name="sms_receiver_idx"),
                ],
            },
        ),
    ]
