# Generated by Django 5.1.2 on 2025-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="is_express",
            field=models.BooleanField(default=False, verbose_name="اکسپرس"),
        ),
        migrations.AlterField(
            model_name="sms",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ آخرین تلاش"),
        ),
        migrations.AlterField(
            model_name="sms",
            name="service_error",
            field=models.TextField(blank=True, verbose_name="خطای سرویس"),
        ),
    ]
