# Generated by Django 5.1.2 on 2025-11-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0002_sms_is_express_alter_sms_last_attempt_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="sender",
            field=models.CharField(max_length=255, verbose_name="شماره فرستنده"),
            preserve_default=False,
        ),
    ]
