# Generated by Django 5.1.2 on 2025-11-11 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("charge", "شارژ حساب"),
                            ("refund", "استرداد"),
                            ("sms_deduction", "کسر پیامک"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="مقدار")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "type"], name="billing_tra_user_id_81db13_idx"),
                    models.Index(fields=["created_at"], name="billing_tra_created_63c54e_idx"),
                ],
            },
        ),
    ]
